export const root = "/"
export const offices = "/locations"
export const devices = "/device/info"
export const ip_ipam = "/network/ipam"
export const reports = "/report/new"

export const reportPhoneByModels = "/report/phoneStatsReport"
export const reportPhoneByClusters = "/report/phoneStatsByClustersReport"
export const reportPhoneByNotUsed = "/report/phoneStatsByNotUsedReport"

export const dictRegions = "/admin/regions"
export const dictCities = "/admin/cities"
export const dictOffice_stats = "/admin/officeStatuses"
export const dictDevices = "/admin/devparts"
export const dictPortTypes = "/admin/portTypes"
export const dictVRFs = "/admin/vrf"
export const dictNetworksTable = "/admin/NetworksTab"

export const HwLogs = "/logs"
export const PhonesLogs = "/logs/phones"
