export const REQUEST_ROOT_ELEMENTS_ID = 'REQUEST_ROOT_ELEMENTS_ID'
export const RECEIVE_ROOT_ELEMENTS_ID = 'RECEIVE_ROOT_ELEMENTS_ID'
export const INVALIDATE_ROOT_ELEMENTS_ID = 'INVALIDATE_ROOT_ELEMENTS_ID'

export const REQUEST_ELEMENTS = 'REQUEST_ELEMENTS'
export const RECEIVE_ELEMENTS = 'RECEIVE_ELEMENTS'
export const INVALIDATE_ELEMENTS = 'INVALIDATE_ELEMENTS'

export const NET_ITEM_TOGGLE_EXPAND_COLLAPSE = 'NET_ITEM_TOGGLE_EXPAND_COLLAPSE'
export const NET_ITEMS_EXPAND = 'NET_ITEMS_EXPAND'
export const UPDATE_NET_ITEMS = 'UPDATE_NET_ITEMS'


export const SET_FILTER = 'SET_FILTER'
export const SET_CURSOR = 'SET_CURSOR'
export const SHOW_RESULT_ITEM = 'SHOW_RESULT_ITEM'
export const BACKUP_NET_ITEMS = 'BACKUP_NET_ITEMS'
// export const REFRESH_STATE_AND_BACKUP = 'REFRESH_STATE_AND_BACKUP'

export const SELECT_NET_ITEMS = 'SELECT_NET_ITEMS'
export const DESELECT_NET_ITEMS = 'DESELECT_NET_ITEMS'
export const SELECT_HOST_ITEMS = 'SELECT_HOST_ITEMS'
export const DESELECT_HOST_ITEMS = 'DESELECT_HOST_ITEMS'

